/**
 * MeetMind Executive PDF Engine
 * Composition Engine v1.0
 *
 * Responsibilities:
 * - normalize report_json into canonical block data;
 * - apply visibility and empty-block filtering;
 * - estimate content mass;
 * - choose density;
 * - preserve immutable business order;
 * - choose adaptive composition templates;
 * - paginate into one or two pages;
 * - produce CompositionResult without coordinates or drawing operations.
 */

import {
  BLOCK_IDS,
  CANONICAL_ORDER,
  COMPOSITION_KIND,
  DENSITY,
  PAGE_KIND,
} from "./composition-types.js";
import {
  COMPOSITION_RULES,
  validateCompositionRules,
} from "./composition-rules.js";

const CONTENT_BLOCKS = new Set([
  BLOCK_IDS.MEETING_STATS,
  BLOCK_IDS.EXECUTIVE_SUMMARY,
  BLOCK_IDS.KEY_METRICS,
  BLOCK_IDS.INSIGHTS,
  BLOCK_IDS.DECISIONS,
  BLOCK_IDS.RISKS,
  BLOCK_IDS.TASKS,
  BLOCK_IDS.ARCHITECTURE,
  BLOCK_IDS.OWNERS,
]);

const ALWAYS_VISIBLE = new Set([BLOCK_IDS.HEADER, BLOCK_IDS.FOOTER]);

/**
 * @param {Object} report
 * @param {import("./composition-types.js").CompositionOptions=} options
 * @returns {import("./composition-types.js").CompositionResult}
 */
export function composeExecutiveReport(report, options = {}) {
  assertPlainObject(report, "report");
  validateCompositionRules(COMPOSITION_RULES);

  const normalized = normalizeReport(report);
  const capacity = resolveCapacity(options.pageCapacity);
  const allowSecondPage = options.allowSecondPage !== false;

  const measured = measureAllBlocks(
    normalized,
    options.visibility ?? {},
    options.preferredDensity,
  );

  const visibleIds = CANONICAL_ORDER.filter((id) => measured[id]?.visible);
  const contentIds = visibleIds.filter((id) => CONTENT_BLOCKS.has(id));

  if (contentIds.length === 0) {
    throw new Error("Composition Engine: report contains no visible content blocks.");
  }

  const pagination = paginate(measured, visibleIds, capacity, allowSecondPage);
  const totalPages = pagination.length;

  const pages = pagination.map((pageBlockIds, index) =>
    createPage({
      index,
      totalPages,
      title: normalized.title,
      date: normalized.date,
      blockIds: pageBlockIds,
      measured,
    }),
  );

  const diagnostics = buildDiagnostics({
    capacity,
    pages,
    measured,
    visibleIds,
  });

  return Object.freeze({
    version: "1.0",
    title: normalized.title,
    date: normalized.date,
    pages: Object.freeze(pages),
    blocks: Object.freeze(measured),
    diagnostics: Object.freeze(diagnostics),
  });
}

export function normalizeReport(report) {
  const meeting = isPlainObject(report.meeting) ? report.meeting : {};
  const title = firstNonEmptyString(
    meeting.title,
    report.title,
    report.meeting_title,
    "Untitled Meeting",
  );

  const rawDate =
    meeting.date ??
    report.date ??
    report.meeting_date ??
    report.created_at ??
    null;

  return {
    title,
    date: normalizeDate(rawDate),
    [BLOCK_IDS.HEADER]: { title, date: normalizeDate(rawDate) },
    [BLOCK_IDS.MEETING_STATS]:
      report.meetingStats ??
      report.meeting_stats ??
      report.stats ??
      buildMeetingStatsFallback(report),
    [BLOCK_IDS.EXECUTIVE_SUMMARY]:
      report.executiveSummary ??
      report.executive_summary ??
      report.meeting_summary ??
      report.summary ??
      null,
    [BLOCK_IDS.KEY_METRICS]:
      report.keyMetrics ??
      report.key_metrics ??
      report.metrics ??
      [],
    [BLOCK_IDS.INSIGHTS]: report.insights ?? [],
    [BLOCK_IDS.DECISIONS]: report.decisions ?? [],
    [BLOCK_IDS.RISKS]: report.risks ?? [],
    [BLOCK_IDS.TASKS]: normalizeTasks(report.tasks ?? report.action_items ?? []),
    [BLOCK_IDS.ARCHITECTURE]:
      report.architecture ??
      report.architecture_sections ??
      null,
    [BLOCK_IDS.OWNERS]:
      report.owners ??
      report.participants ??
      [],
    [BLOCK_IDS.FOOTER]: {
      brand: "MeetMind AI",
      text: "Generated by MeetMind AI",
    },
  };
}

function measureAllBlocks(normalized, visibility, preferredDensity) {
  /** @type {Record<string, import("./composition-types.js").MeasuredBlock>} */
  const result = {};

  for (const id of CANONICAL_ORDER) {
    const data = normalized[id];
    const required = ALWAYS_VISIBLE.has(id);
    const enabled = required || visibility[id] !== false;
    const empty = !required && isEmptyBlock(id, data);
    const visible = enabled && !empty;

    const raw = measureBlock(id, data);
    const density = resolveInitialDensity(raw.mass, preferredDensity);
    const adjustedMass = applyDensity(raw.mass, density);

    result[id] = Object.freeze({
      id,
      data,
      itemCount: raw.itemCount,
      textLength: raw.textLength,
      mass: round(adjustedMass),
      density,
      visible,
      required,
    });
  }

  return result;
}

export function measureBlock(id, data) {
  const base = COMPOSITION_RULES.blockBaseMass[id] ?? 5;
  const itemCount = countItems(id, data);
  const textLength = countTextLength(data);
  const itemMass = COMPOSITION_RULES.measurement.itemMass[id] ?? 0;
  const textMass = Math.min(
    textLength / COMPOSITION_RULES.measurement.charsPerMassUnit,
    COMPOSITION_RULES.measurement.maximumTextContribution,
  );

  return {
    itemCount,
    textLength,
    mass: Math.max(base, base + itemCount * itemMass + textMass),
  };
}

function paginate(measured, visibleIds, capacity, allowSecondPage) {
  let pageOne = visibleIds.slice();
  let pageTwo = [];

  pageOne = ensureBoundaryBlocks(pageOne);
  let pageOneMass = sumMass(pageOne, measured);

  if (pageOneMass <= capacity) {
    return [pageOne];
  }

  pageOne = compactPage(pageOne, measured, capacity);
  pageOneMass = sumMass(pageOne, measured);

  if (pageOneMass <= capacity) {
    return [pageOne];
  }

  if (!allowSecondPage) {
    pageOne = densifyPage(pageOne, measured);
    return [pageOne];
  }

  for (const transferableId of COMPOSITION_RULES.overflowTransferOrder) {
    if (pageOneMass <= capacity) break;
    if (!pageOne.includes(transferableId)) continue;

    pageOne = pageOne.filter((id) => id !== transferableId);
    pageTwo.push(transferableId);
    pageOneMass = sumMass(pageOne, measured);
  }

  if (pageOneMass > capacity) {
    pageOne = densifyPage(pageOne, measured);
  }

  pageTwo = CANONICAL_ORDER.filter((id) => pageTwo.includes(id));
  if (pageTwo.length === 0) {
    return [pageOne];
  }

  // Header and footer repeat on continuation pages by contract.
  const continuation = [
    BLOCK_IDS.HEADER,
    ...pageTwo.filter((id) => id !== BLOCK_IDS.HEADER && id !== BLOCK_IDS.FOOTER),
    BLOCK_IDS.FOOTER,
  ];

  return [ensureBoundaryBlocks(pageOne), ensureBoundaryBlocks(continuation)];
}

function createPage({ index, totalPages, title, date, blockIds, measured }) {
  const pageNumber = index + 1;
  const kind = index === 0 ? PAGE_KIND.EXECUTIVE : PAGE_KIND.CONTINUATION;
  const pageIndicator = totalPages > 1 ? `${pageNumber}/${totalPages}` : null;
  const regions = buildRegions(blockIds, measured, kind);

  return Object.freeze({
    number: pageNumber,
    totalPages,
    kind,
    title,
    date,
    pageIndicator,
    blockIds: Object.freeze(blockIds.slice()),
    regions: Object.freeze(regions),
    estimatedMass: round(sumMass(blockIds, measured)),
  });
}

function buildRegions(blockIds, measured, pageKind) {
  const regions = [];
  const has = (id) => blockIds.includes(id);

  appendSingle(regions, BLOCK_IDS.HEADER, has);
  appendSingle(regions, BLOCK_IDS.MEETING_STATS, has);
  appendSingle(regions, BLOCK_IDS.EXECUTIVE_SUMMARY, has);
  appendSingle(regions, BLOCK_IDS.KEY_METRICS, has);

  const trioIds = [
    BLOCK_IDS.INSIGHTS,
    BLOCK_IDS.DECISIONS,
    BLOCK_IDS.RISKS,
  ].filter(has);

  if (trioIds.length > 0) {
    regions.push(buildExecutiveTrioRegion(trioIds, measured));
  }

  const hasTasks = has(BLOCK_IDS.TASKS);
  const hasArchitecture = has(BLOCK_IDS.ARCHITECTURE);

  if (
    hasTasks &&
    hasArchitecture &&
    canPlaceTasksAndArchitectureSideBySide(measured)
  ) {
    regions.push({
      kind: COMPOSITION_KIND.TASKS_ARCHITECTURE_SIDE_BY_SIDE,
      blockIds: [BLOCK_IDS.TASKS, BLOCK_IDS.ARCHITECTURE],
      columns: [0.58, 0.42],
      density: maxDensity([
        measured[BLOCK_IDS.TASKS].density,
        measured[BLOCK_IDS.ARCHITECTURE].density,
      ]),
    });
  } else {
    if (hasTasks) {
      regions.push({
        kind: COMPOSITION_KIND.TASKS_FULL_WIDTH,
        blockIds: [BLOCK_IDS.TASKS],
        columns: [1],
        density: measured[BLOCK_IDS.TASKS].density,
      });
    }
    appendSingle(regions, BLOCK_IDS.ARCHITECTURE, has, measured);
  }

  appendSingle(regions, BLOCK_IDS.OWNERS, has, measured);
  appendSingle(regions, BLOCK_IDS.FOOTER, has);

  if (pageKind === PAGE_KIND.CONTINUATION) {
    return regions.map((region) => ({
      ...region,
      metadata: {
        ...(region.metadata ?? {}),
        continuation: true,
      },
    }));
  }

  return regions;
}

function buildExecutiveTrioRegion(ids, measured) {
  if (ids.length === 1) {
    return {
      kind: COMPOSITION_KIND.STACK,
      blockIds: ids,
      columns: [1],
      density: measured[ids[0]].density,
    };
  }

  if (ids.length === 2) {
    return {
      kind: COMPOSITION_KIND.STACK,
      blockIds: ids,
      columns: [0.5, 0.5],
      density: maxDensity(ids.map((id) => measured[id].density)),
      metadata: { preserveOrder: true },
    };
  }

  const masses = Object.fromEntries(ids.map((id) => [id, measured[id].mass]));
  const dominantId = findDominantBlock(ids, masses);

  if (!dominantId) {
    return {
      kind: COMPOSITION_KIND.BALANCED_EXECUTIVE_TRIO,
      blockIds: ids,
      columns: [1 / 3, 1 / 3, 1 / 3],
      density: maxDensity(ids.map((id) => measured[id].density)),
      metadata: { preserveOrder: true },
    };
  }

  if (dominantId === BLOCK_IDS.INSIGHTS) {
    return {
      kind: COMPOSITION_KIND.DOMINANT_INSIGHTS,
      blockIds: ids,
      columns: [1, 0.5, 0.5],
      density: maxDensity(ids.map((id) => measured[id].density)),
      metadata: {
        rows: [
          [BLOCK_IDS.INSIGHTS],
          [BLOCK_IDS.DECISIONS, BLOCK_IDS.RISKS],
        ],
        preserveOrder: true,
      },
    };
  }

  if (dominantId === BLOCK_IDS.DECISIONS) {
    return {
      kind: COMPOSITION_KIND.DOMINANT_DECISIONS,
      blockIds: ids,
      columns: [1],
      density: maxDensity(ids.map((id) => measured[id].density)),
      metadata: {
        rows: [
          [BLOCK_IDS.INSIGHTS],
          [BLOCK_IDS.DECISIONS],
          [BLOCK_IDS.RISKS],
        ],
        preserveOrder: true,
      },
    };
  }

  return {
    kind: COMPOSITION_KIND.DOMINANT_RISKS,
    blockIds: ids,
    columns: [0.5, 0.5, 1],
    density: maxDensity(ids.map((id) => measured[id].density)),
    metadata: {
      rows: [
        [BLOCK_IDS.INSIGHTS, BLOCK_IDS.DECISIONS],
        [BLOCK_IDS.RISKS],
      ],
      preserveOrder: true,
    },
  };
}

function findDominantBlock(ids, masses) {
  const sorted = ids
    .map((id) => ({ id, mass: masses[id] }))
    .sort((a, b) => b.mass - a.mass);

  const largest = sorted[0];
  const second = sorted[1];

  if (largest.mass < COMPOSITION_RULES.dominance.minimumMass) {
    return null;
  }

  if (largest.mass / Math.max(second.mass, 1) < COMPOSITION_RULES.dominance.ratio) {
    return null;
  }

  return largest.id;
}

function canPlaceTasksAndArchitectureSideBySide(measured) {
  const tasks = measured[BLOCK_IDS.TASKS];
  const architecture = measured[BLOCK_IDS.ARCHITECTURE];
  if (!tasks?.visible || !architecture?.visible) return false;

  return (
    tasks.mass <= COMPOSITION_RULES.sideBySide.maxSingleMass &&
    architecture.mass <= COMPOSITION_RULES.sideBySide.maxSingleMass &&
    tasks.mass + architecture.mass <=
      COMPOSITION_RULES.sideBySide.maxCombinedMass
  );
}

function compactPage(blockIds, measured, capacity) {
  const compactableIds = blockIds.filter(
    (id) => !ALWAYS_VISIBLE.has(id) && measured[id].density === DENSITY.REGULAR,
  );

  for (const id of compactableIds) {
    if (sumMass(blockIds, measured) <= capacity) break;
    replaceMeasuredDensity(measured, id, DENSITY.COMPACT);
  }

  return blockIds;
}

function densifyPage(blockIds, measured) {
  for (const id of blockIds) {
    if (!ALWAYS_VISIBLE.has(id)) {
      replaceMeasuredDensity(measured, id, DENSITY.DENSE);
    }
  }
  return blockIds;
}

function replaceMeasuredDensity(measured, id, targetDensity) {
  const current = measured[id];
  if (!current) return;

  const currentMultiplier =
    COMPOSITION_RULES.density.massMultiplier[current.density] ?? 1;
  const targetMultiplier =
    COMPOSITION_RULES.density.massMultiplier[targetDensity] ?? 1;
  const rawMass = current.mass / currentMultiplier;

  measured[id] = Object.freeze({
    ...current,
    density: targetDensity,
    mass: round(rawMass * targetMultiplier),
  });
}

function resolveInitialDensity(mass, preferredDensity) {
  if (Object.values(DENSITY).includes(preferredDensity)) {
    return preferredDensity;
  }

  const capacity = COMPOSITION_RULES.page.defaultCapacity;
  if (mass >= capacity * COMPOSITION_RULES.density.denseThreshold) {
    return DENSITY.DENSE;
  }
  if (mass >= capacity * COMPOSITION_RULES.density.compactThreshold) {
    return DENSITY.COMPACT;
  }
  return DENSITY.REGULAR;
}

function applyDensity(mass, density) {
  const multiplier =
    COMPOSITION_RULES.density.massMultiplier[density] ?? 1;
  return mass * multiplier;
}

function resolveCapacity(candidate) {
  if (candidate == null) return COMPOSITION_RULES.page.defaultCapacity;
  if (!Number.isFinite(candidate)) {
    throw new TypeError("Composition Engine: pageCapacity must be a finite number.");
  }

  return Math.min(
    COMPOSITION_RULES.page.maximumCapacity,
    Math.max(COMPOSITION_RULES.page.minimumUsefulCapacity, candidate),
  );
}

function ensureBoundaryBlocks(ids) {
  const withoutBoundaries = ids.filter(
    (id) => id !== BLOCK_IDS.HEADER && id !== BLOCK_IDS.FOOTER,
  );
  return [BLOCK_IDS.HEADER, ...withoutBoundaries, BLOCK_IDS.FOOTER];
}

function appendSingle(regions, id, has, measured = null) {
  if (!has(id)) return;
  regions.push({
    kind: COMPOSITION_KIND.STACK,
    blockIds: [id],
    columns: [1],
    density: measured?.[id]?.density,
  });
}

function countItems(id, data) {
  if (Array.isArray(data)) return data.length;

  if (id === BLOCK_IDS.ARCHITECTURE && isPlainObject(data)) {
    const sections = Array.isArray(data.sections) ? data.sections : [];
    if (sections.length > 0) {
      return sections.reduce((total, section) => {
        const items = Array.isArray(section?.items) ? section.items.length : 0;
        return total + Math.max(1, items);
      }, 0);
    }
    if (Array.isArray(data.items)) return data.items.length;
  }

  if (isPlainObject(data)) {
    return Object.keys(data).filter((key) => !isEmptyValue(data[key])).length;
  }

  return isEmptyValue(data) ? 0 : 1;
}

function countTextLength(value, seen = new WeakSet()) {
  if (value == null) return 0;
  if (typeof value === "string") return value.trim().length;
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value).length;
  }

  if (Array.isArray(value)) {
    return value.reduce((sum, item) => sum + countTextLength(item, seen), 0);
  }

  if (isPlainObject(value)) {
    if (seen.has(value)) return 0;
    seen.add(value);
    return Object.values(value).reduce(
      (sum, item) => sum + countTextLength(item, seen),
      0,
    );
  }

  return 0;
}

function isEmptyBlock(id, data) {
  if (id === BLOCK_IDS.MEETING_STATS && isPlainObject(data)) {
    return Object.values(data).every(isEmptyValue);
  }
  return isEmptyValue(data);
}

function isEmptyValue(value) {
  if (value == null) return true;
  if (typeof value === "string") return value.trim().length === 0;
  if (Array.isArray(value)) return value.length === 0;
  if (isPlainObject(value)) return Object.keys(value).length === 0;
  return false;
}

function normalizeTasks(tasks) {
  if (!Array.isArray(tasks)) return [];

  return tasks.map((task) => {
    if (!isPlainObject(task)) {
      return { task: String(task), owner: null, due: null };
    }

    return {
      ...task,
      task:
        task.task ??
        task.title ??
        task.description ??
        "",
      owner:
        task.owner ??
        task.assignee ??
        null,
      due:
        task.due ??
        task.due_date ??
        task.dueDate ??
        task.deadline ??
        null,
    };
  });
}

function buildMeetingStatsFallback(report) {
  const participants = Array.isArray(report.participants)
    ? report.participants.length
    : null;
  const tasks = Array.isArray(report.tasks) ? report.tasks.length : null;
  const decisions = Array.isArray(report.decisions)
    ? report.decisions.length
    : null;
  const risks = Array.isArray(report.risks) ? report.risks.length : null;

  return {
    participants,
    tasks,
    decisions,
    risks,
  };
}

function normalizeDate(value) {
  if (value == null || value === "") return null;

  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }

  if (typeof value === "string") {
    const trimmed = value.trim();
    const isoDate = trimmed.match(/^(\d{4}-\d{2}-\d{2})/);
    if (isoDate) return isoDate[1];

    const parsed = new Date(trimmed);
    if (!Number.isNaN(parsed.getTime())) {
      return parsed.toISOString().slice(0, 10);
    }

    return trimmed;
  }

  return String(value);
}

function buildDiagnostics({ capacity, pages, measured, visibleIds }) {
  const warnings = [];

  for (const page of pages) {
    if (page.estimatedMass > capacity) {
      warnings.push(
        `Page ${page.number} estimated mass ${page.estimatedMass} exceeds capacity ${capacity}.`,
      );
    }
  }

  return {
    capacity,
    pageCount: pages.length,
    visibleBlockIds: visibleIds.slice(),
    blockMasses: Object.fromEntries(
      visibleIds.map((id) => [id, measured[id].mass]),
    ),
    warnings,
  };
}

function sumMass(ids, measured) {
  return ids.reduce((sum, id) => sum + (measured[id]?.mass ?? 0), 0);
}

function maxDensity(densities) {
  if (densities.includes(DENSITY.DENSE)) return DENSITY.DENSE;
  if (densities.includes(DENSITY.COMPACT)) return DENSITY.COMPACT;
  return DENSITY.REGULAR;
}

function firstNonEmptyString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim();
  }
  return "Untitled Meeting";
}

function assertPlainObject(value, name) {
  if (!isPlainObject(value)) {
    throw new TypeError(`Composition Engine: ${name} must be a plain object.`);
  }
}

function isPlainObject(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    (Object.getPrototypeOf(value) === Object.prototype ||
      Object.getPrototypeOf(value) === null)
  );
}

function round(value) {
  return Math.round(value * 100) / 100;
}
