/* eslint-disable no-console */
'use strict';

const assert = require('assert');
const pipelineApi = require('./pdf-pipeline.js');
const renderer = require('./renderer.js');
const renderContextApi = require('./render-context.js');

const calls = [];

const drawingSurface = {
    currentPage: null,

    createPage(size, page) {
        this.currentPage = page.number;
        calls.push(['createPage', page.number, size.width, size.height]);
    },

    getCurrentPage() {
        return this.currentPage;
    },

    drawText(page, text, geometry) {
        calls.push(['text', page, text, geometry.x, geometry.y]);
    },

    drawRect(page, geometry) {
        calls.push(['rect', page, geometry.x, geometry.y]);
    },

    drawLine() {},
    drawIcon() {},
    drawTable() {},

    finalize(layoutResult) {
        calls.push(['finalize', layoutResult.pageCount]);
        return { kind: 'mock-document' };
    }
};

const blockRegistry = {
    get(id) {
        return { renderer: id };
    }
};

const blockRenderers = {
    header(block, context) {
        context.text(
            block.data?.title || 'Meeting',
            block.geometry,
            {}
        );
    },

    summary(block, context) {
        context.rect(block.geometry, {});
        context.text(
            block.data?.text || '',
            block.geometry,
            {}
        );
    },

    footer(block, context) {
        context.text(
            'Generated by MeetMind AI',
            block.geometry,
            {}
        );
    }
};

function compose(report) {
    return {
        pages: [{
            number: 1,
            blocks: [
                { id: 'header', data: { title: report.title } },
                { id: 'summary', data: { text: report.summary } },
                { id: 'footer' }
            ]
        }]
    };
}

function layout(composition) {
    return {
        pageCount: 1,
        valid: true,
        pages: [{
            id: 'page-1',
            number: 1,
            index: 0,
            size: { width: 1600, height: 900 },
            blocks: composition.pages[0].blocks.map((block, index) => ({
                ...block,
                geometry: {
                    x: 48,
                    y: 40 + index * 120,
                    width: 1504,
                    height: index === 1 ? 100 : 62
                }
            }))
        }]
    };
}

const renderContext = renderContextApi.create(drawingSurface);
const pipeline = pipelineApi.create({
    compose,
    layout,
    render: (layoutResult, context) =>
        renderer.render(layoutResult, context, {
            blockRegistry,
            blockRenderers
        })
});

const result = pipeline.run(
    {
        title: 'Weekly Review',
        summary: 'MVP scope approved.'
    },
    { renderContext }
);

assert.strictEqual(result.layoutResult.pageCount, 1);
assert.strictEqual(result.renderResult.pageCount, 1);
assert.deepStrictEqual(
    result.renderResult.pages[0].blockIds,
    ['header', 'summary', 'footer']
);
assert.ok(calls.some(call => call[0] === 'createPage'));
assert.ok(calls.some(call => call[0] === 'rect'));
assert.ok(calls.some(call => call[0] === 'finalize'));

console.log('MeetMind Renderer Integration 0.4 smoke test: PASSED');
